# Generated by Django 3.0.2 on 2020-01-17 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mesures', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='captureco2',
            name='capteur',
            field=models.CharField(default=302, max_length=16),
            preserve_default=False,
        ),
    ]
