# Generated by Django 3.0.2 on 2020-02-03 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mesures', '0003_auto_20200203_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='captureco2',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
